### ISSUE TITLE
Needless locking on writing out all log entries

### ISSUE THREAD

**Issue by veqryn** [ventu-io/slog#5]
The method `handleall` in `logger.go` writes out all log lines/entries to all handlers.
It locks in order to get the list of handlers:
```go
	f.RLock()
	handlers := make([]EntryHandler, len(f.handlers))
	copy(handlers, f.handlers)
	f.RUnlock()
```

I feel this is unneeded: how often are people adding more handlers long after the initialization of their logger?
All handlers should be added in the `init()` method of the `main` package that sets up the logger.  LogFactory should be immutable after initialization.

If there is truly a use for this, then perhaps have a simple check for whether the user wants to be able to add/remove handlers, that way you don't have to lock for each log item written unless the user really wants that behavior.

**Comment by osklyar** [comment]
I had this same thought originally and only introduced locking later when a performance test did not show any difference at all whether we have it here or not. So it is needless as it could hamper performance, not because it is not something that cannot go wrong here. Is performance really noticeably affected (I think I have a test that runs a millions logs or something)?

**Comment by veqryn** [comment]
I can't say how much, if at all, removing the locking would improve performance.  It just seemed unneeded from reading the code and from an architecture point of view.

**Comment by osklyar** [comment]
So for the moment we could do with flipping the concurrent switch to false. The other change about synchronising the handlers would need more thought.

**Comment by osklyar** [comment]
TestVoidHandler_nonconcurrent_performance_1e6Under4s and TestVoidHandler_concurrent_performance_1e6Under4s with or without that lock each of them completes in about the same time 1.1s on my hardware. Both tests output 1mil logs. Btw, if you work on concurrency and joining the goroutines these are the ones to look at.

I keep it as is because even the case of running into an issue here is artificial the cost is negligible IMHO.
